spring.application.name=WineAdvisor

# MongoDB connection configuration
spring.data.mongodb.database=wineadvisor
spring.data.mongodb.uri=mongodb://10.1.1.22:27018,10.1.1.21:27018,10.1.1.20:27018/?replicaSet=wineadvisor_repl_set&retryWrites=true&w=1&readPreference=nearest
#spring.data.mongodb.server-selection-timeout=5000         #timeout in millisecondi: decommentare se si vuole impostare un timeout non di default

# Neo4j connection configuration
spring.neo4j.uri=bolt://10.1.1.20:7687
# spring.neo4j.authentication.database=neo4j    # decommentare e cambiare il nome del database se non si vuole usare il db predefinito "neo4j"
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=wineadvisor


# --- LOCALHOST CONFIGURATION ---
# # MongoDB connection configuration
# spring.data.mongodb.database=wineadvisor
# spring.data.mongodb.uri=mongodb://localhost:27017/
# #spring.data.mongodb.server-selection-timeout=5000         #timeout in millisecondi: decommentare se si vuole impostare un timeout non di default

# # Neo4j connection configuration
# spring.neo4j.uri=bolt://localhost:7687
# # spring.neo4j.authentication.database=neo4j    # decommentare e cambiare il nome del database se non si vuole usare il db predefinito "neo4j"
# spring.neo4j.authentication.username=neo4j
# spring.neo4j.authentication.password=wineadvisor
